services:
  frontend:
    build:
      context: ./WEB-IS2
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./WEB-IS2/:/app
      - node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: >
      sh -c "npm install --legacy-peer-deps && npm run dev -- --host 0.0.0.0"

  backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      environment:
        - PYTHONPATH=/app
      ports:
        - "8000:8000"
      volumes:
        - ./backend:/app
      command: >
        sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  node_modules: